Create Actions file
Levliv/Python_HomeWorks_4semester pull request #1
Opened 2022-03-04 15:14 UTC by Levliv

2022-03-04 18:52 UTC, SpirinEgor requested changes

2022-03-04 18:52 UTC, SpirinEgor commented on .github/workflows/main.yml
> +          if [-d SRC]; then black . --check -l 120; fi
1. Зачем заглавными?
2. Проверяется одна папка, но запускается black на другой
3. Black можно и без проверки запускать

2022-03-04 19:02 UTC, Levliv commented on .github/workflows/main.yml
> +          if [-d SRC]; then black . --check -l 120; fi
Да, идея была запускать black для всех py файлов, так что лучше эту проверку вообще убрать.

2022-03-08 10:40 UTC, SpirinEgor approved these changes

2022-03-08 10:40 UTC, merged